### ISSUE TITLE
Showcase page is really buggy on my android phone. 

### ISSUE THREAD

**Issue by arkydon** [UWPCommunity/uwpcommunity.github.io#105]
On my android phone on browsers the "See Showcase" page of the site is messed up. It takes quite a bit of time to load like 3 or 4 minutes and when it does finish loading, half the page is cut off. Scrolling is really jittery and laggy.

My phone is a Mi A2, its really snappy and doesn't have problem opening heavy sites, my internet is also superfast fiber wifi internet.

**Comment by Arlodotexe** [comment]
The launch showcase is a separate project and has not yet been fully optimized. This will be fixed in the future, likely around the next launch event.
