### ISSUE TITLE
Navigate Outside of current tab?

### ISSUE THREAD

**Issue by avknaidu** [UWPCommunity/uwpcommunity.github.io#79]
When you click on any Icon with Links ( Store Icon / Github Icon / Site Icon ), it navigates to that link in same tab. Do you think its a good idea to open a new tab by default?

Also when you navigate back, instead of Tab title "UWP Community // Projects" It says "UWP Community // 404"

**Comment by Arlodotexe** [comment]
I'd like to make this happen, but the [DocumentCard](https://developer.microsoft.com/en-us/fluentui#/controls/web/documentcard)  [Actions](https://docs.microsoft.com/en-us/javascript/api/office-ui-fabric-react/idocumentcardactionsprops?view=office-ui-fabric-react-latest) we're using doesn't allow this. We would have to do a refactor to remove use of the Actions.

**Comment by Arlodotexe** [comment]
User can ctrl + click or right click to open in new tab. Closing issue.
